# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory to /app
WORKDIR /backend

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV DJANGO_SETTINGS_MODULE=backend.settings

# Run the command when the container starts
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
